name: nutri_vision_app
description: "Projeto NutriVision - Scanner de Calorias"
version: 1.0.0+1

# ADICIONE ESTAS LINHAS AQUI:
environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI/Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.1 # Gerenciamento de rotas
  
  # State Management
  provider: ^6.0.5 # Gerenciamento de estado
  
  # Environment & Utils
  flutter_dotenv: ^5.1.0 # Para carregar .env files
  # flutter_flavorizr: ^2.1.1 # Opcional, para automação de flavors (se for usar)
  intl: ^0.18.1 # Para formatação de datas, números, etc.
  logger: ^2.0.2+1 # Para logs mais bonitos no console
  
  # Firebase
  firebase_core: ^2.24.0 # Core do Firebase
  firebase_auth: ^4.15.0 # Autenticação
  cloud_firestore: ^4.13.3 # Banco de dados NoSQL
  firebase_storage: ^11.5.3 # Armazenamento de arquivos
  
  # Imagens/Assets
  flutter_svg: ^2.0.9 # Para usar ícones SVG
  
  # Design & Utilities
  percent_indicator: ^4.2.3 # Para os círculos de progresso (Kcal, TMB)
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # Melhores práticas de linting
  
  # Ferramentas para assets (opcional, mas recomendado)
  flutter_launcher_icons: "^0.13.1" # Gerar ícones do app
  flutter_native_splash: "^2.3.6"   # Gerar tela de splash nativa

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env.dev
    - .env.prod

  fonts:
    - family: Inter # Exemplo de fonte customizada (você pode usar uma equivalente às suas designs)
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

# Configuração para flutter_launcher_icons (exemplo)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_nutrivision.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# Configuração para flutter_native_splash (exemplo)
flutter_native_splash:
  color: "#FFFFFF" # Cor de fundo da tela de splash
  image: assets/images/logo_nutrivision.png
  android: true
  ios: true
  web: false # Se não for para web
